spring.application.name=alfa

# Configuração da Porta dinâmica (Render atribui uma porta automática)
server.port=${PORT:8080}

# Conexão com o PostgreSQL via Variáveis de Ambiente
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/alfa_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

